name: Run Lint
description: Reusable action to lint the app

runs:
  using: 'composite'
  steps:
    - name: Check out Git repository
      uses: actions/checkout@v4

    - name: Install Node.js and NPM
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: npm

    - name: npm install
      run: npm install
      shell: bash

    - name: npm run lint
      run: npm run lint
      shell: bash
