name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  actions: read
  issues: write
  pull-requests: write

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests using reusable action
        uses: ./.github/actions/test
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  publish-release:
    needs: test
    runs-on: windows-latest

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --latest --strip all
        env:
          OUTPUT: CHANGES.md
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}

      - name: Install Node and NPM
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install and build
        run: |
          npm install
          npm run postinstall
          npm run build

      - name: Publish releases
        shell: pwsh
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: electron-builder
        run: |
          npm exec -- electron-builder --publish=always --win --draft=false --prerelease=false

      - name: Update release notes
        shell: bash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release edit "${{ github.ref_name }}" --notes-file CHANGES.md
